Repository BVictorB/friendship, pull requests merged in 2020-06, with the labels that each got.

#19 Improvement/homepage
  src/routes/index.js
  src/views/includes/section_boardgames.ejs
  src/views/includes/section_comics.ejs
  src/views/includes/section_users.ejs
Labels: enhancement

#20 Added activation mail feature
  package-lock.json
  package.json
  src/router.js
  src/routes/activate.js
  src/routes/loginpost.js
  src/routes/registerpost.js
  src/user.js
  src/views/includes/login-user.ejs
  static/js/loginValidate.js
Labels: enhancement

#22 Improvement/searchpage
  src/router.js
  src/routes/index.js
  src/routes/search.js
  src/views/includes/section_result.ejs
  src/views/search.ejs
Labels: enhancement

#32 Merge staging into master branch
  index.js
  package-lock.json
  package.json
  src/multer.js
  src/router.js
  src/routes/activate.js
  src/routes/index.js
  src/routes/loginpost.js
  src/routes/logout.js
  src/routes/registerpost.js
  src/routes/search.js
  src/user.js
  src/views/includes/header.ejs
  src/views/includes/login-user.ejs
  src/views/includes/section_boardgames.ejs
  src/views/includes/section_comics.ejs
  src/views/includes/section_result.ejs
  src/views/includes/section_users.ejs
  src/views/register.ejs
  src/views/search.ejs
  static/css/style.css
  static/js/loginValidate.js
  static/js/script.js
  static/js/signupValidate.js
  static/uploads/1590840347427.jpeg
  static/uploads/1590840521206.jpeg
  static/uploads/1590840605587.jpeg
  static/uploads/1590840689986.jpeg
  static/uploads/1590840769489.jpeg
Labels: enhancement

#40 Feature/filter
  src/router.js
  src/routes/search.js
  src/views/includes/filter.ejs
  src/views/includes/no-result.ejs
  src/views/includes/section_fit.ejs
  src/views/includes/section_random_users.ejs
  src/views/includes/section_result.ejs
  src/views/search.ejs
  static/css/style.css
  static/images/no-result.jpg
Labels: enhancement

#58 Feature/load api
  index.js
  package-lock.json
  src/router.js
  src/routes/index.js
  src/views/includes/scripts.ejs
  src/views/includes/section_weather.ejs
  src/views/index.ejs
  static/css/style.css
  static/images/cloud-sun.svg
  static/images/cloud.svg
  static/images/games.jpg
  static/images/mtb.jpg
  static/images/rain.svg
  static/images/snow.svg
  static/images/sunny.svg
  static/js/weather.js
Labels: enhancement

#65 Improvement/styling
  index.js
  package-lock.json
  package.json
  src/router.js
  src/routes/index.js
  src/routes/likepost.js
  src/routes/loginpost.js
  src/routes/profilepost.js
  src/routes/registerpost.js
  src/styles/global/_base.scss
  src/styles/global/_fonts.scss
  src/styles/global/_mixins.scss
  src/styles/global/_variables.scss
  src/styles/main-screen.scss
  src/styles/modules/_m-category.scss
  src/styles/modules/_m-form.scss
  src/styles/modules/_m-nav.scss
  src/styles/modules/_m-users.scss
  src/styles/pages/_p-home.scss
  src/styles/pages/_p-login.scss
  src/styles/pages/_p-profile.scss
  src/styles/pages/_p-register.scss
  src/styles/pages/_p-search.scss
  src/styles/vendor/_normalize.scss
  src/styles/vendor/normalize/_variables.scss
  src/styles/vendor/normalize/_vertical-rhythm.scss
  src/user.js
  src/views/includes/head.ejs
  src/views/includes/header.ejs
  src/views/includes/login-user.ejs
  src/views/includes/scripts.ejs
  src/views/includes/section_users.ejs
  src/views/index.ejs
  src/views/login.ejs
  src/views/profile.ejs
  src/views/register.ejs
  static/images/pen.svg
  static/js/editProfile.js
  static/js/navMenu.js
  static/js/script.js
  static/js/signupValidate.js
  static/styles/main-screen.css
  static/uploads/1592497248028.jpg
  static/uploads/1592515964443.jpg
  static/uploads/1592524204879.jpg
  static/uploads/1592524645968.jpg
  static/uploads/1592529836303.jpg
  static/uploads/1592575481912.jpg
Labels: backend, frontend

#87 Improvement/load api back end
  package-lock.json
  package.json
  src/routes/index.js
  src/static/js/weather.js
  src/views/includes/section_weather.ejs
Labels: enhancement

#94 filter results without your own profile and matches
  src/routes/search.js
Labels: backend, bug

#98 avatar images
  src/static/uploads/1592816690608.jpg
  src/static/uploads/1592816956753.jpg
  src/static/uploads/1592817600056.jpg
  src/static/uploads/1592817724253.jpg
  src/static/uploads/1592817953635.jpg
  src/static/uploads/1592820172897.jpg
  src/static/uploads/1592820250542.jpg
  src/static/uploads/1592820318831.jpg
  src/static/uploads/1592820377564.jpg
  src/static/uploads/1592820450909.jpg
  src/static/uploads/1592820526247.jpg
Labels: frontend

#109 Improved styling
  index.js
  src/static/images/logo-part-left.png
  src/static/images/logo-part-right.png
  src/static/js/editProfile.js
  src/static/js/signupValidate.js
  src/static/styles/main-screen.css
  src/styles/global/_global.scss
  src/styles/main-screen.scss
  src/styles/modules/_m-background.scss
  src/styles/modules/_m-users.scss
  src/styles/pages/_p-home.scss
  src/styles/pages/_p-matches.scss
  src/styles/pages/_p-profile.scss
  src/styles/pages/_p-register.scss
  src/views/includes/section_users.ejs
  src/views/partials/shared/html-open.ejs
  src/views/profile.ejs
  src/views/register.ejs
Labels: bug, enhancement, frontend

#110 added Helmet
  index.js
Labels: backend, enhancement

#107 Improvement/readme
  README.md
Labels: documentation

#113 Email
  src/routes/registerpost.js
  src/static/styles/main-screen.css
  src/styles/pages/_p-register.scss
  src/utils/executeEmail.js
Labels: backend, enhancement
